version: '3.7'
services:
  react-app:
    image: react-app
    build: ./client/
    stdin_open: true
    ports:
      - 3001:3001
    networks:
      - mern-app
    volumes:
      - ./client/:/usr/src/app/
   
  api-server:
    image: api-server
    build: ./server/
    stdin_open: true
    ports:
      - 5001:5001
    networks:
      - mern-app
    depends_on:
      - mongo
    volumes:
      - ./server/:/usr/src/app/
  mongo:
    image: mongo:latest
    stdin_open: true
    ports:
      - 27017:27017
    networks:
      - mern-app
    volumes:
      - ./mongo-data:/data/db
   
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
   